import json
import os
import sys
from datetime import datetime

DOCS_DIR    = "docs"
API_DIR     = "api"
REPORT_PATH = "sync_report.txt"
OBSOLETE    = "[УСТАРЕЛО]"

DB_CONFIG = {
    "type":     "",
    "host":     "",
    "port":     0000,
    "database": "",
    "user":     "",
    "password": "",
}

# Описание принадлежности таблиц к конкретному блоку
BLOCK_TABLES = {
    "contacts": {
        "contacts": {
            "description": "Хранит контактную информацию сервиса",
            "relations":   ["city_id → city.city_id"],
            "usage":       ["Страница «Контакты»", "API-метод: GET /api/contacts"],

        },
    },
}

# Чтение схемы из БД
def get_schema_from_db(config: dict) -> dict:
    db_type = config["type"].lower()

    if db_type == "mysql":
        try:
            import pymysql
        except ImportError:
            print("Установите: pip install pymysql")
            sys.exit(1)
        conn  = pymysql.connect(
            host=config["host"], port=int(config["port"]),
            database=config["database"],
            user=config["user"], password=config["password"],
            charset="utf8mb4"
        )
        query = """
            SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = %s
            ORDER BY TABLE_NAME, ORDINAL_POSITION
        """
        cur = conn.cursor()
        cur.execute(query, (config["database"],))

    elif db_type == "postgresql":
        try:
            import psycopg2
        except ImportError:
            print("Установите: pip install psycopg2-binary")
            sys.exit(1)
        conn  = psycopg2.connect(
            host=config["host"], port=int(config["port"]),
            dbname=config["database"],
            user=config["user"], password=config["password"]
        )
        query = """
            SELECT table_name, column_name, data_type, is_nullable
            FROM information_schema.columns
            WHERE table_schema = 'public'
            ORDER BY table_name, ordinal_position
        """
        cur = conn.cursor()
        cur.execute(query)
    else:
        print(f"Неизвестный тип БД: {db_type}")
        sys.exit(1)

    rows   = cur.fetchall()
    cur.close()
    conn.close()

    tables = {}
    for table_name, col_name, data_type, is_nullable in rows:
        if table_name not in tables:
            tables[table_name] = []
        tables[table_name].append({
            "name":     col_name,
            "type":     data_type,
            "nullable": is_nullable.upper() == "YES",
        })

    print(f"  Прочитано таблиц из БД: {len(tables)}")
    return tables

# Чтение API из JSON
def load_api_methods(block_name: str) -> list:
    path = os.path.join(API_DIR, f"{block_name}.json")
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data.get("methods", [])


SECTION_SCENARIOS  = "## Пользовательские сценарии"
SECTION_DIAGRAMS   = "## Диаграммы"
SECTION_DB         = "## База данных"
SECTION_API        = "## API-методы"

AUTOGEN_START = "<!-- AUTOGENERATED START -->"
AUTOGEN_END   = "<!-- AUTOGENERATED END -->"


def extract_manual_sections(md_text: str) -> dict:
    """
    Извлекаем из файла секции написанные вручную
    (сценарии и диаграммы) — их скрипт не трогает.
    """
    sections = {
        "scenarios": "",
        "diagrams":  "",
    }

    lines          = md_text.splitlines()
    current        = None
    collecting     = []
    auto_skip      = False

    for line in lines:
        if AUTOGEN_START in line:
            auto_skip = True
            continue
        if AUTOGEN_END in line:
            auto_skip = False
            continue
        if auto_skip:
            continue

        if line.startswith(SECTION_SCENARIOS):
            if current and collecting:
                sections[current] = "\n".join(collecting).strip()
            current    = "scenarios"
            collecting = []
            continue
        if line.startswith(SECTION_DIAGRAMS):
            if current and collecting:
                sections[current] = "\n".join(collecting).strip()
            current    = "diagrams"
            collecting = []
            continue
        if line.startswith(SECTION_DB) or line.startswith(SECTION_API):
            if current and collecting:
                sections[current] = "\n".join(collecting).strip()
            current    = None
            collecting = []
            continue
        if line.startswith("## ") and current:
            sections[current] = "\n".join(collecting).strip()
            current    = None
            collecting = []
            continue

        if current:
            collecting.append(line)

    if current and collecting:
        sections[current] = "\n".join(collecting).strip()

    return sections


def parse_db_fields_from_md(md_text: str, table_name: str) -> dict:
    """
    Извлекаем задокументированные поля конкретной таблицы из Markdown-файла.
    Сохраняем уже заполненные назначения и примеры.
    """
    result     = {}
    in_table   = False
    in_fields  = False

    for line in md_text.splitlines():
        if f"### Таблица `{table_name}`" in line:
            in_table  = True
            in_fields = False
            continue
        if in_table and line.startswith("### Таблица"):
            break
        if in_table and "| Название параметра |" in line:
            in_fields = True
            continue
        if in_table and in_fields and "---" in line:
            continue
        if in_table and in_fields and line.startswith("|"):
            parts = [p.strip() for p in line.strip("|").split("|")]
            if len(parts) >= 5:
                raw  = parts[0]
                name = raw.replace(OBSOLETE, "").strip()
                result[name] = {
                    "name":     name,
                    "type":     parts[1],
                    "nullable": parts[2] == "да",
                    "purpose":  parts[3],
                    "example":  parts[4],
                    "obsolete": OBSOLETE in raw,
                }

    return result


# Генерация автоматических секций
def render_db_section(block_name: str, all_tables: dict,
                      existing_md: str) -> tuple[str, list]:
    """Генерируем блок БД с назначением, связями и применением."""
    block_meta  = BLOCK_TABLES.get(block_name, {})
    table_names = list(block_meta.keys())
    changes     = []
    lines       = []

    for tname in table_names:
        meta          = block_meta.get(tname, {})
        actual_fields = {f["name"]: f for f in all_tables.get(tname, [])}
        doc_fields    = parse_db_fields_from_md(existing_md, tname)

        lines.append(f"### Таблица `{tname}`")
        lines.append("")

        desc = meta.get("description", "_Требует описания_")
        lines.append(f"**Назначение:** {desc}")
        lines.append("")

        relations = meta.get("relations", [])
        if relations:
            lines.append(f"**Связи:** {'; '.join(relations)}")
        else:
            lines.append("**Связи:** Отсутствуют")
        lines.append("")

        usage = meta.get("usage", [])
        if usage:
            lines.append(f"**Применение:** {'; '.join(usage)}")
        lines.append("")

        if not actual_fields:
            lines.append(f"_Таблица `{tname}` не найдена в схеме БД._")
            lines.append("")
            continue

        merged = []

        for fname, df in doc_fields.items():
            if fname in actual_fields:
                af       = actual_fields[fname]
                new_type = af["type"]
                if df.get("obsolete"):
                    changes.append(
                        f"  ↩ [{tname}] поле '{fname}' восстановлено"
                    )
                elif df["type"] != new_type:
                    changes.append(
                        f"  ~ [{tname}] поле '{fname}': "
                        f"'{df['type']}' → '{new_type}'"
                    )
                merged.append({
                    "name":     fname,
                    "type":     new_type,
                    "nullable": af["nullable"],
                    "purpose":  df["purpose"],
                    "example":  df["example"],
                    "obsolete": False,
                })
            else:
                if not df.get("obsolete"):
                    changes.append(
                        f"  ✗ [{tname}] поле '{fname}' → {OBSOLETE}"
                    )
                merged.append({**df, "obsolete": True})

        for fname, af in actual_fields.items():
            if fname not in doc_fields:
                merged.append({
                    "name":     fname,
                    "type":     af["type"],
                    "nullable": af["nullable"],
                    "purpose":  "_Требует описания_",
                    "example":  "_Требует примера_",
                    "obsolete": False,
                })
                changes.append(
                    f"  + [{tname}] новое поле '{fname}' ({af['type']})"
                )

        lines.append("| Название параметра | Тип данных | Может быть пустым? | Назначение | Пример |")
        lines.append("| :--- | :--- | :---: | :--- | :--- |")

        for f in merged:
            name = f"{OBSOLETE} {f['name']}" if f.get("obsolete") else f["name"]
            lines.append(
                f"| {name} | {f['type']} "
                f"| {'да' if f['nullable'] else 'нет'} "
                f"| {f['purpose']} | {f['example']} |"
            )
        lines.append("")

    return "\n".join(lines), changes


def render_api_section(methods: list) -> tuple[str, list]:
    """Генерируем блок API"""
    if not methods:
        return "_API-методы для данного блока не описаны._\n", []

    changes = [f"  ↻ API-секция обновлена ({len(methods)} методов)"]
    lines   = []

    for m in methods:
        lines.append(f"### `{m['http']} {m['uri']}`")
        lines.append("")
        # Паспорт метода
        lines.append(f"**Назначение:** {m.get('description', '_Не указано_')}")
        lines.append(f"**Авторизация:** {'Требуется' if m.get('auth') else 'Не требуется'}")

        usage = m.get("usage", [])
        if usage:
            lines.append(f"**Применение:** {'; '.join(usage)}")

        tables = m.get("db_tables", [])
        if tables:
            lines.append(f"**Таблицы БД:** {', '.join(tables)}")

        lines.append("")

        # Входные параметры
        req_params = m.get("request_params", [])
        if req_params:
            lines.append("**Входные параметры:**")
            lines.append("")
            lines.append("| № | Название | Где | Тип | Обязателен? | Формат | Пример |")
            lines.append("| --- | --- | --- | --- | --- | --- | --- |")
            for i, p in enumerate(req_params, 1):
                req = "да" if p.get("required") else "нет"
                lines.append(
                    f"| {i} | {p['name']} | {p.get('location','—')} "
                    f"| {p['type']} | {req} "
                    f"| {p.get('format','—')} | {p.get('example','—')} |"
                )
            lines.append("")

        # Карта ответов
        responses = m.get("responses", [])
        if responses:
            lines.append("**Карта ответов:**")
            lines.append("")
            lines.append("| Код | Условие | Формат | Описание |")
            lines.append("| --- | --- | --- | --- |")
            for r in responses:
                lines.append(
                    f"| {r['code']} | {r['condition']} "
                    f"| {r.get('format','JSON')} | {r['description']} |"
                )
            lines.append("")

        # Поля ответа
        resp_fields = m.get("response_fields", [])
        if resp_fields:
            lines.append("**Поля ответа:**")
            lines.append("")
            lines.append("| № | Название | Тип | Обязателен? | Назначение | Пример |")
            lines.append("| --- | --- | --- | --- | --- | --- |")
            for i, f in enumerate(resp_fields, 1):
                req = "да" if f.get("required") else "нет"
                lines.append(
                    f"| {i} | {f['name']} | {f['type']} | {req} "
                    f"| {f.get('purpose','—')} | {f.get('example','—')} |"
                )
            lines.append("")

    return "\n".join(lines), changes


# Сборка итогового Markdown-файла блока
def build_block_file(block_name: str, manual: dict,
                     db_content: str, api_content: str) -> str:
    title = block_name.replace("_", " ").capitalize()
    lines = []

    lines.append(f"# Блок: {title}")
    lines.append("")
    lines.append(
        f"_Автоматически обновлено: "
        f"{datetime.now().strftime('%d.%m.%Y %H:%M')}_"
    )
    lines.append("")

    # Уровень 1 — сценарии (ручная секция)
    lines.append(SECTION_SCENARIOS)
    lines.append("")
    if manual.get("scenarios"):
        lines.append(manual["scenarios"])
    else:
        lines.append("_Пользовательские сценарии заполняются вручную._")
    lines.append("")

    # Уровень 2 — диаграммы (ручная секция)
    lines.append(SECTION_DIAGRAMS)
    lines.append("")
    if manual.get("diagrams"):
        lines.append(manual["diagrams"])
    else:
        lines.append("_Диаграммы вставляются вручную._")
    lines.append("")

    # Уровень 3 — БД
    lines.append(SECTION_DB)
    lines.append("")
    lines.append(db_content)
    lines.append("")

    # Уровень 3 — API
    lines.append(SECTION_API)
    lines.append("")
    lines.append(api_content)
    lines.append("")

    return "\n".join(lines)

def sync_all(all_tables: dict) -> str:
    """Синхронизируем все блоки. Возвращаем отчёт."""
    os.makedirs(DOCS_DIR, exist_ok=True)
    os.makedirs(API_DIR,  exist_ok=True)

    report        = []
    total_changes = 0

    report.append("=" * 65)
    report.append("ОТЧЁТ О СИНХРОНИЗАЦИИ ДОКУМЕНТАЦИИ")
    report.append(f"Дата: {datetime.now().strftime('%d.%m.%Y %H:%M')}")
    report.append("=" * 65)
    report.append("")

    for block_name in BLOCK_TABLES:
        doc_path    = os.path.join(DOCS_DIR, f"{block_name}.md")
        existing_md = ""

        if os.path.exists(doc_path):
            with open(doc_path, encoding="utf-8") as f:
                existing_md = f.read()

        manual = extract_manual_sections(existing_md)

        db_content, db_changes = render_db_section(
            block_name, all_tables, existing_md
        )

        api_methods             = load_api_methods(block_name)
        api_content, api_changes = render_api_section(api_methods)

        all_changes = db_changes + api_changes

        new_md = build_block_file(block_name, manual, db_content, api_content)
        with open(doc_path, "w", encoding="utf-8") as f:
            f.write(new_md)

        if all_changes:
            report.append(f"[ ОБНОВЛЕНО ] {block_name}.md")
            report.extend(all_changes)
            total_changes += len(all_changes)
        else:
            report.append(f"[ БЕЗ ИЗМЕНЕНИЙ ] {block_name}.md")

        report.append("")

    report.append("=" * 65)
    if total_changes == 0:
        report.append("✓ Документация актуальна.")
    else:
        report.append(f"Синхронизация завершена. Изменений: {total_changes}")
        report.append(
            "Поля '_Требует описания_' необходимо заполнить вручную."
        )
    report.append("=" * 65)

    return "\n".join(report)

def main():
    print("=" * 65)
    print("Синхронизация документации программной системы")
    print("=" * 65)
    print(
        f"Подключение к {DB_CONFIG['type']} "
        f"{DB_CONFIG['host']}:{DB_CONFIG['port']} ..."
    )
    try:
        all_tables = get_schema_from_db(DB_CONFIG)
        print("Подключение успешно.\n")
    except Exception as e:
        print(f"\nОшибка подключения: {e}")
        print("Проверьте настройки DB_CONFIG в начале файла.")
        sys.exit(1)

    report = sync_all(all_tables)
    print(report)

    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\nОтчёт сохранён: {REPORT_PATH}")
    print(f"Документация обновлена в папке: {DOCS_DIR}/")


if __name__ == "__main__":
    main()